In [17]:
import sys
from datasets import load_dataset

sys.path.append('../../')
from src.utils.memory_utils import process_in_chunks

# LOAD DATASETS
user_data = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023", 
    "raw_review_CDs_and_Vinyl", 
    split="full", 
    trust_remote_code=True
)

meta = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023", 
    "raw_meta_CDs_and_Vinyl", 
    split="full", 
    trust_remote_code=True
)

# FLATTEN LIST COLUMNS IN METADATA
def flatten_lst(col):
    """Flatten lists by joining their elements with a separator (e.g., ', ')"""
    col['features'] = ', '.join(col['features']) if isinstance(col['features'], list) else col['features']
    col['description'] = ', '.join(col['description']) if isinstance(col['description'], list) else col['description']
    col['categories'] = ', '.join(col['categories']) if isinstance(col['categories'], list) else col['categories']
    return col

flattened_meta = meta.map(flatten_lst)

# CONVERT TO PANDAS WITH CHUNK PROCESSING
user_df = process_in_chunks(user_data.to_pandas(), chunk_size=10000)
meta_df = process_in_chunks(flattened_meta.to_pandas(), chunk_size=10000)

# user_df = user_data.to_pandas().fillna(0)
# meta_df = flattened_meta.to_pandas().fillna(0)

Processed 0 rows. Current memory usage: 1544.41 MB
Processed 10000 rows. Current memory usage: 1557.83 MB
Processed 20000 rows. Current memory usage: 1564.72 MB
Processed 30000 rows. Current memory usage: 1560.86 MB
Processed 40000 rows. Current memory usage: 1539.06 MB
Processed 50000 rows. Current memory usage: 1540.73 MB
Processed 60000 rows. Current memory usage: 1542.55 MB
Processed 70000 rows. Current memory usage: 1549.16 MB
Processed 80000 rows. Current memory usage: 1554.70 MB
Processed 90000 rows. Current memory usage: 1561.03 MB
Processed 100000 rows. Current memory usage: 1565.00 MB
Processed 110000 rows. Current memory usage: 1545.41 MB
Processed 120000 rows. Current memory usage: 1552.73 MB
Processed 130000 rows. Current memory usage: 1559.25 MB
Processed 140000 rows. Current memory usage: 1566.05 MB
Processed 150000 rows. Current memory usage: 1571.72 MB
Processed 160000 rows. Current memory usage: 1578.53 MB
Processed 170000 rows. Current memory usage: 1584.38 MB
Processed 180000 rows. Current memory usage: 1591.28 MB
Processed 190000 rows. Current memory usage: 1597.52 MB
Processed 200000 rows. Current memory usage: 1603.88 MB
Processed 210000 rows. Current memory usage: 1609.45 MB
Processed 220000 rows. Current memory usage: 1615.61 MB
Processed 230000 rows. Current memory usage: 1621.64 MB
Processed 240000 rows. Current memory usage: 1628.95 MB
Processed 250000 rows. Current memory usage: 1635.48 MB
Processed 260000 rows. Current memory usage: 1641.66 MB
Processed 270000 rows. Current memory usage: 1648.02 MB
Processed 280000 rows. Current memory usage: 1648.91 MB
Processed 290000 rows. Current memory usage: 1615.95 MB
Processed 300000 rows. Current memory usage: 1586.61 MB
Processed 310000 rows. Current memory usage: 1534.17 MB
Processed 320000 rows. Current memory usage: 1485.52 MB
Processed 330000 rows. Current memory usage: 1492.52 MB
Processed 340000 rows. Current memory usage: 1499.69 MB
Processed 350000 rows. Current memory usage: 1506.98 MB
Processed 360000 rows. Current memory usage: 1514.84 MB
Processed 370000 rows. Current memory usage: 1525.61 MB
Processed 380000 rows. Current memory usage: 1534.91 MB
Processed 390000 rows. Current memory usage: 1543.52 MB
Processed 400000 rows. Current memory usage: 1550.48 MB
Processed 410000 rows. Current memory usage: 1556.66 MB
Processed 420000 rows. Current memory usage: 1564.47 MB
Processed 430000 rows. Current memory usage: 1573.98 MB
Processed 440000 rows. Current memory usage: 1580.45 MB
Processed 450000 rows. Current memory usage: 1587.23 MB
Processed 460000 rows. Current memory usage: 1587.14 MB
Processed 470000 rows. Current memory usage: 1537.36 MB
Processed 480000 rows. Current memory usage: 1539.16 MB
Processed 490000 rows. Current memory usage: 1464.11 MB
Processed 500000 rows. Current memory usage: 1451.14 MB
Processed 510000 rows. Current memory usage: 1452.05 MB
Processed 520000 rows. Current memory usage: 1445.80 MB
Processed 530000 rows. Current memory usage: 1451.69 MB
Processed 540000 rows. Current memory usage: 1459.09 MB
Processed 550000 rows. Current memory usage: 1461.22 MB
Processed 560000 rows. Current memory usage: 1466.44 MB
Processed 570000 rows. Current memory usage: 1474.50 MB
Processed 580000 rows. Current memory usage: 1485.75 MB
Processed 590000 rows. Current memory usage: 1482.89 MB
Processed 600000 rows. Current memory usage: 1489.91 MB
Processed 610000 rows. Current memory usage: 1492.97 MB
Processed 620000 rows. Current memory usage: 1485.52 MB
Processed 630000 rows. Current memory usage: 1445.06 MB
Processed 640000 rows. Current memory usage: 1451.78 MB
Processed 650000 rows. Current memory usage: 1458.62 MB
Processed 660000 rows. Current memory usage: 1465.25 MB
Processed 670000 rows. Current memory usage: 1476.11 MB
Processed 680000 rows. Current memory usage: 1484.70 MB
Processed 690000 rows. Current memory usage: 1491.67 MB
Processed 700000 rows. Current memory usage: 1499.38 MB
Processed 710000 rows. Current memory usage: 1507.59 MB
Processed 720000 rows. Current memory usage: 1514.70 MB
Processed 730000 rows. Current memory usage: 1521.42 MB
Processed 740000 rows. Current memory usage: 1531.33 MB
Processed 750000 rows. Current memory usage: 1539.45 MB
Processed 760000 rows. Current memory usage: 1546.45 MB
Processed 770000 rows. Current memory usage: 1557.22 MB
Processed 780000 rows. Current memory usage: 1565.28 MB
Processed 790000 rows. Current memory usage: 1576.31 MB
Processed 800000 rows. Current memory usage: 1587.11 MB
Processed 810000 rows. Current memory usage: 1597.23 MB
Processed 820000 rows. Current memory usage: 1607.20 MB
Processed 830000 rows. Current memory usage: 1551.97 MB
Processed 840000 rows. Current memory usage: 1553.91 MB
Processed 850000 rows. Current memory usage: 1563.11 MB
Processed 860000 rows. Current memory usage: 1573.28 MB
Processed 870000 rows. Current memory usage: 1582.77 MB
Processed 880000 rows. Current memory usage: 1592.42 MB
Processed 890000 rows. Current memory usage: 1599.73 MB
Processed 900000 rows. Current memory usage: 1607.47 MB
Processed 910000 rows. Current memory usage: 1616.06 MB
Processed 920000 rows. Current memory usage: 1624.41 MB
Processed 930000 rows. Current memory usage: 1631.31 MB
Processed 940000 rows. Current memory usage: 1638.28 MB
Processed 950000 rows. Current memory usage: 1630.95 MB
Processed 960000 rows. Current memory usage: 1622.28 MB
Processed 970000 rows. Current memory usage: 1598.25 MB
Processed 980000 rows. Current memory usage: 1605.36 MB
Processed 990000 rows. Current memory usage: 1613.94 MB
Processed 1000000 rows. Current memory usage: 1619.95 MB
Processed 1010000 rows. Current memory usage: 1626.52 MB
Processed 1020000 rows. Current memory usage: 1633.02 MB
Processed 1030000 rows. Current memory usage: 1639.75 MB
Processed 1040000 rows. Current memory usage: 1647.05 MB
Processed 1050000 rows. Current memory usage: 1654.17 MB
Processed 1060000 rows. Current memory usage: 1660.58 MB
Processed 1070000 rows. Current memory usage: 1666.94 MB
Processed 1080000 rows. Current memory usage: 1645.14 MB
Processed 1090000 rows. Current memory usage: 1597.98 MB
Processed 1100000 rows. Current memory usage: 1605.38 MB
Processed 1110000 rows. Current memory usage: 1613.27 MB
Processed 1120000 rows. Current memory usage: 1621.25 MB
Processed 1130000 rows. Current memory usage: 1627.84 MB
Processed 1140000 rows. Current memory usage: 1637.61 MB
Processed 1150000 rows. Current memory usage: 1648.88 MB
Processed 1160000 rows. Current memory usage: 1656.58 MB
Processed 1170000 rows. Current memory usage: 1663.17 MB
Processed 1180000 rows. Current memory usage: 1672.75 MB
Processed 1190000 rows. Current memory usage: 1683.56 MB
Processed 1200000 rows. Current memory usage: 1690.56 MB
Processed 1210000 rows. Current memory usage: 1699.48 MB
Processed 1220000 rows. Current memory usage: 1705.97 MB
Processed 1230000 rows. Current memory usage: 1713.53 MB
Processed 1240000 rows. Current memory usage: 1676.73 MB
Processed 1250000 rows. Current memory usage: 1659.03 MB
Processed 1260000 rows. Current memory usage: 1621.80 MB
Processed 1270000 rows. Current memory usage: 1624.84 MB
Processed 1280000 rows. Current memory usage: 1635.36 MB
Processed 1290000 rows. Current memory usage: 1643.39 MB
Processed 1300000 rows. Current memory usage: 1650.95 MB
Processed 1310000 rows. Current memory usage: 1658.81 MB
Processed 1320000 rows. Current memory usage: 1667.66 MB
Processed 1330000 rows. Current memory usage: 1649.56 MB
Processed 1340000 rows. Current memory usage: 1656.45 MB
Processed 1350000 rows. Current memory usage: 1664.38 MB
Processed 1360000 rows. Current memory usage: 1673.73 MB
Processed 1370000 rows. Current memory usage: 1674.95 MB
Processed 1380000 rows. Current memory usage: 1650.39 MB
Processed 1390000 rows. Current memory usage: 1652.05 MB
Processed 1400000 rows. Current memory usage: 1628.39 MB
Processed 1410000 rows. Current memory usage: 1600.28 MB
Processed 1420000 rows. Current memory usage: 1557.23 MB
Processed 1430000 rows. Current memory usage: 1566.20 MB
Processed 1440000 rows. Current memory usage: 1575.06 MB
Processed 1450000 rows. Current memory usage: 1591.67 MB
Processed 1460000 rows. Current memory usage: 1606.50 MB
Processed 1470000 rows. Current memory usage: 1616.75 MB
Processed 1480000 rows. Current memory usage: 1624.61 MB
Processed 1490000 rows. Current memory usage: 1646.06 MB
Processed 1500000 rows. Current memory usage: 1654.48 MB
Processed 1510000 rows. Current memory usage: 1664.11 MB
Processed 1520000 rows. Current memory usage: 1669.45 MB
Processed 1530000 rows. Current memory usage: 1624.75 MB
Processed 1540000 rows. Current memory usage: 1633.42 MB
Processed 1550000 rows. Current memory usage: 1641.34 MB
Processed 1560000 rows. Current memory usage: 1648.80 MB
Processed 1570000 rows. Current memory usage: 1651.64 MB
Processed 1580000 rows. Current memory usage: 1659.14 MB
Processed 1590000 rows. Current memory usage: 1666.97 MB
Processed 1600000 rows. Current memory usage: 1666.53 MB
Processed 1610000 rows. Current memory usage: 1592.69 MB
Processed 1620000 rows. Current memory usage: 1601.23 MB
Processed 1630000 rows. Current memory usage: 1609.00 MB
Processed 1640000 rows. Current memory usage: 1618.19 MB
Processed 1650000 rows. Current memory usage: 1625.22 MB
Processed 1660000 rows. Current memory usage: 1631.86 MB
Processed 1670000 rows. Current memory usage: 1638.72 MB
Processed 1680000 rows. Current memory usage: 1645.72 MB
Processed 1690000 rows. Current memory usage: 1655.20 MB
Processed 1700000 rows. Current memory usage: 1666.77 MB
Processed 1710000 rows. Current memory usage: 1674.14 MB
Processed 1720000 rows. Current memory usage: 1680.27 MB
Processed 1730000 rows. Current memory usage: 1690.62 MB
Processed 1740000 rows. Current memory usage: 1691.14 MB
Processed 1750000 rows. Current memory usage: 1698.08 MB
Processed 1760000 rows. Current memory usage: 1705.06 MB
Processed 1770000 rows. Current memory usage: 1705.53 MB
Processed 1780000 rows. Current memory usage: 1684.23 MB
Processed 1790000 rows. Current memory usage: 1691.41 MB
Processed 1800000 rows. Current memory usage: 1662.22 MB
Processed 1810000 rows. Current memory usage: 1544.11 MB
Processed 1820000 rows. Current memory usage: 1555.38 MB
Processed 1830000 rows. Current memory usage: 1563.89 MB
Processed 1840000 rows. Current memory usage: 1571.92 MB
Processed 1850000 rows. Current memory usage: 1580.64 MB
Processed 1860000 rows. Current memory usage: 1587.41 MB
Processed 1870000 rows. Current memory usage: 1594.61 MB
Processed 1880000 rows. Current memory usage: 1601.69 MB
Processed 1890000 rows. Current memory usage: 1604.58 MB
Processed 1900000 rows. Current memory usage: 1605.06 MB
Processed 1910000 rows. Current memory usage: 1600.83 MB
Processed 1920000 rows. Current memory usage: 1601.34 MB
Processed 1930000 rows. Current memory usage: 1600.02 MB
Processed 1940000 rows. Current memory usage: 1593.05 MB
Processed 1950000 rows. Current memory usage: 1602.67 MB
Processed 1960000 rows. Current memory usage: 1609.50 MB
Processed 1970000 rows. Current memory usage: 1616.78 MB
Processed 1980000 rows. Current memory usage: 1613.25 MB
Processed 1990000 rows. Current memory usage: 1588.84 MB
Processed 2000000 rows. Current memory usage: 1596.53 MB
Processed 2010000 rows. Current memory usage: 1594.12 MB
Processed 2020000 rows. Current memory usage: 1602.05 MB
Processed 2030000 rows. Current memory usage: 1612.98 MB
Processed 2040000 rows. Current memory usage: 1623.83 MB
Processed 2050000 rows. Current memory usage: 1635.92 MB
Processed 2060000 rows. Current memory usage: 1640.95 MB
Processed 2070000 rows. Current memory usage: 1649.69 MB
Processed 2080000 rows. Current memory usage: 1664.30 MB
Processed 2090000 rows. Current memory usage: 1669.91 MB
Processed 2100000 rows. Current memory usage: 1681.62 MB
Processed 2110000 rows. Current memory usage: 1684.61 MB
Processed 2120000 rows. Current memory usage: 1693.58 MB
Processed 2130000 rows. Current memory usage: 1698.23 MB
Processed 2140000 rows. Current memory usage: 1706.03 MB
Processed 2150000 rows. Current memory usage: 1697.73 MB
Processed 2160000 rows. Current memory usage: 1708.47 MB
Processed 2170000 rows. Current memory usage: 1687.92 MB
Processed 2180000 rows. Current memory usage: 1654.66 MB
Processed 2190000 rows. Current memory usage: 1613.45 MB
Processed 2200000 rows. Current memory usage: 1619.42 MB
Processed 2210000 rows. Current memory usage: 1629.28 MB
Processed 2220000 rows. Current memory usage: 1641.23 MB
Processed 2230000 rows. Current memory usage: 1653.69 MB
Processed 2240000 rows. Current memory usage: 1665.58 MB
Processed 2250000 rows. Current memory usage: 1678.83 MB
Processed 2260000 rows. Current memory usage: 1688.47 MB
Processed 2270000 rows. Current memory usage: 1695.55 MB
Processed 2280000 rows. Current memory usage: 1703.67 MB
Processed 2290000 rows. Current memory usage: 1710.58 MB
Processed 2300000 rows. Current memory usage: 1717.62 MB
Processed 2310000 rows. Current memory usage: 1724.19 MB
Processed 2320000 rows. Current memory usage: 1727.31 MB
Processed 2330000 rows. Current memory usage: 1735.52 MB
Processed 2340000 rows. Current memory usage: 1708.88 MB
Processed 2350000 rows. Current memory usage: 1715.97 MB
Processed 2360000 rows. Current memory usage: 1708.81 MB
Processed 2370000 rows. Current memory usage: 1651.09 MB
Processed 2380000 rows. Current memory usage: 1658.59 MB
Processed 2390000 rows. Current memory usage: 1611.17 MB
Processed 2400000 rows. Current memory usage: 1618.62 MB
Processed 2410000 rows. Current memory usage: 1626.31 MB
Processed 2420000 rows. Current memory usage: 1634.86 MB
Processed 2430000 rows. Current memory usage: 1643.44 MB
Processed 2440000 rows. Current memory usage: 1650.66 MB
Processed 2450000 rows. Current memory usage: 1659.12 MB
Processed 2460000 rows. Current memory usage: 1661.12 MB
Processed 2470000 rows. Current memory usage: 1668.34 MB
Processed 2480000 rows. Current memory usage: 1677.42 MB
Processed 2490000 rows. Current memory usage: 1689.66 MB
Processed 2500000 rows. Current memory usage: 1704.31 MB
Processed 2510000 rows. Current memory usage: 1714.75 MB
Processed 2520000 rows. Current memory usage: 1722.08 MB
Processed 2530000 rows. Current memory usage: 1702.59 MB
Processed 2540000 rows. Current memory usage: 1713.78 MB
Processed 2550000 rows. Current memory usage: 1721.66 MB
Processed 2560000 rows. Current memory usage: 1699.88 MB
Processed 2570000 rows. Current memory usage: 1631.97 MB
Processed 2580000 rows. Current memory usage: 1645.00 MB
Processed 2590000 rows. Current memory usage: 1655.94 MB
Processed 2600000 rows. Current memory usage: 1666.89 MB
Processed 2610000 rows. Current memory usage: 1675.14 MB
Processed 2620000 rows. Current memory usage: 1684.41 MB
Processed 2630000 rows. Current memory usage: 1694.56 MB
Processed 2640000 rows. Current memory usage: 1703.05 MB
Processed 2650000 rows. Current memory usage: 1711.55 MB
Processed 2660000 rows. Current memory usage: 1719.55 MB
Processed 2670000 rows. Current memory usage: 1727.31 MB
Processed 2680000 rows. Current memory usage: 1724.81 MB
Processed 2690000 rows. Current memory usage: 1733.61 MB
Processed 2700000 rows. Current memory usage: 1743.09 MB
Processed 2710000 rows. Current memory usage: 1752.27 MB
Processed 2720000 rows. Current memory usage: 1760.14 MB
Processed 2730000 rows. Current memory usage: 1769.25 MB
Processed 2740000 rows. Current memory usage: 1763.36 MB
Processed 2750000 rows. Current memory usage: 1747.83 MB
Processed 2760000 rows. Current memory usage: 1717.69 MB
Processed 2770000 rows. Current memory usage: 1675.86 MB
Processed 2780000 rows. Current memory usage: 1684.94 MB
Processed 2790000 rows. Current memory usage: 1695.69 MB
Processed 2800000 rows. Current memory usage: 1704.47 MB
Processed 2810000 rows. Current memory usage: 1712.28 MB
Processed 2820000 rows. Current memory usage: 1721.38 MB
Processed 2830000 rows. Current memory usage: 1723.86 MB
Processed 2840000 rows. Current memory usage: 1732.58 MB
Processed 2850000 rows. Current memory usage: 1744.19 MB
Processed 2860000 rows. Current memory usage: 1746.88 MB
Processed 2870000 rows. Current memory usage: 1729.77 MB
Processed 2880000 rows. Current memory usage: 1737.58 MB
Processed 2890000 rows. Current memory usage: 1748.00 MB
Processed 2900000 rows. Current memory usage: 1719.28 MB
Processed 2910000 rows. Current memory usage: 1727.77 MB
Processed 2920000 rows. Current memory usage: 1731.28 MB
Processed 2930000 rows. Current memory usage: 1720.17 MB
Processed 2940000 rows. Current memory usage: 1704.16 MB
Processed 2950000 rows. Current memory usage: 1702.30 MB
Processed 2960000 rows. Current memory usage: 1644.86 MB
Processed 2970000 rows. Current memory usage: 1654.75 MB
Processed 2980000 rows. Current memory usage: 1663.81 MB
Processed 2990000 rows. Current memory usage: 1672.11 MB
Processed 3000000 rows. Current memory usage: 1680.23 MB
Processed 3010000 rows. Current memory usage: 1689.20 MB
Processed 3020000 rows. Current memory usage: 1531.81 MB
Processed 3030000 rows. Current memory usage: 1320.14 MB
Processed 3040000 rows. Current memory usage: 1332.16 MB
Processed 3050000 rows. Current memory usage: 1343.70 MB
Processed 3060000 rows. Current memory usage: 1332.44 MB
Processed 3070000 rows. Current memory usage: 1315.08 MB
Processed 3080000 rows. Current memory usage: 1320.78 MB
Processed 3090000 rows. Current memory usage: 1316.70 MB
Processed 3100000 rows. Current memory usage: 1328.59 MB
Processed 3110000 rows. Current memory usage: 1300.28 MB
Processed 3120000 rows. Current memory usage: 1311.80 MB
Processed 3130000 rows. Current memory usage: 1327.09 MB
Processed 3140000 rows. Current memory usage: 1338.11 MB
Processed 3150000 rows. Current memory usage: 1350.48 MB
Processed 3160000 rows. Current memory usage: 1363.81 MB
Processed 3170000 rows. Current memory usage: 1375.98 MB
Processed 3180000 rows. Current memory usage: 1356.48 MB
Processed 3190000 rows. Current memory usage: 1290.38 MB
Processed 3200000 rows. Current memory usage: 1277.56 MB
Processed 3210000 rows. Current memory usage: 1291.36 MB
Processed 3220000 rows. Current memory usage: 1304.41 MB
Processed 3230000 rows. Current memory usage: 1317.86 MB
Processed 3240000 rows. Current memory usage: 1330.97 MB
Processed 3250000 rows. Current memory usage: 1343.31 MB
Processed 3260000 rows. Current memory usage: 1354.97 MB
Processed 3270000 rows. Current memory usage: 1366.34 MB
Processed 3280000 rows. Current memory usage: 1376.72 MB
Processed 3290000 rows. Current memory usage: 1387.48 MB
Processed 3300000 rows. Current memory usage: 1398.70 MB
Processed 3310000 rows. Current memory usage: 1407.50 MB
Processed 3320000 rows. Current memory usage: 1399.66 MB
Processed 3330000 rows. Current memory usage: 1409.23 MB
Processed 3340000 rows. Current memory usage: 1416.27 MB
Processed 3350000 rows. Current memory usage: 1419.47 MB
Processed 3360000 rows. Current memory usage: 1429.20 MB
Processed 3370000 rows. Current memory usage: 1440.17 MB
Processed 3380000 rows. Current memory usage: 1449.95 MB
Processed 3390000 rows. Current memory usage: 1459.58 MB
Processed 3400000 rows. Current memory usage: 1468.69 MB
Processed 3410000 rows. Current memory usage: 1478.19 MB
Processed 3420000 rows. Current memory usage: 1487.30 MB
Processed 3430000 rows. Current memory usage: 1494.47 MB
Processed 3440000 rows. Current memory usage: 1502.72 MB
Processed 3450000 rows. Current memory usage: 1511.50 MB
Processed 3460000 rows. Current memory usage: 1519.78 MB
Processed 3470000 rows. Current memory usage: 1528.25 MB
Processed 3480000 rows. Current memory usage: 1530.06 MB
Processed 3490000 rows. Current memory usage: 1515.47 MB
Processed 3500000 rows. Current memory usage: 1524.33 MB
Processed 3510000 rows. Current memory usage: 1503.73 MB

In [18]:
user_df['verified_purchase'] = user_df['verified_purchase'].astype(int)
user_df.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,0,1
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,0,1
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,0,1
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,3,1
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,0,0

In [19]:
user_df['rating'] = user_df['rating'].astype('float32')
user_df.groupby(['rating','verified_purchase']).size().reset_index().pivot(columns='rating', index='verified_purchase', values=0)

rating                1.0    2.0     3.0     4.0      5.0
verified_purchase
0                   81604  63704  117798  288213   996369
1                  106123  76853  165893  376301  2554415

In [20]:
user_df2 = user_df[['rating', 'asin', 'parent_asin', 'user_id', 'timestamp', 'text']]
user_df2

,rating,asin,parent_asin,user_id,timestamp,text
0,5.0,B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650777000,LOVE IT!
1,5.0,B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452650764000,LOVE!!
2,3.0,B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,1452649885000,Sad there is not the versions with the real/or...
3,3.0,B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,1164036864000,I have listen to The Broadway 1958 Flower Drum...
4,5.0,B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1582090199946,Simply great album. One of the best. Marvelous...
...,...,...,...,...,...,...
4827268,5.0,B000002VPH,B000002VPH,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308413175000,I love this cd and love the movie thank u I ha...
4827269,5.0,B000084T18,B000084T18,AHM36UEBOF2I6VH7CGAGHCDDUITQ,1308412875000,I love the cd it play real well and was delive...
4827270,5.0,B004OFWLO0,B004OFWLO0,AHRJPHOI5JHYEQVSDMNX6736QH3Q,1505425559120,Such a great remaster you can fully appreciate...
4827271,1.0,B000GIXIAK,B000GIXIAK,AH4PJ73QN75AJM5VSCT53AOADCGA,1157470110000,What this CD is lacking is a heart. The music...
4827272,5.0,B0001ADALU,B0001ADALU,AH4PJ73QN75AJM5VSCT53AOADCGA,1077661382000,I am VERY impressed with this album as I was e...

In [21]:
# drop cols dont provide contextual meaning
user_df = user_df.drop(['images'], axis='columns')

In [22]:
meta_df.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Digital Music,Release Some Tension,4.601562,112,,Swv ~ Release Some Tension,12.05,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",SWV Format: Audio CD,"CDs & Vinyl, Dance & Electronic, House","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000002X4C,None,None,None
1,Digital Music,Rio Angie,5.000000,1,,"Shrimp City Slim (aka Gary Erwin, b. 1953, Chi...",14.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Shrimp City Slim (Artist) Format: Audio CD,"CDs & Vinyl, Jazz, Avant Garde & Free Jazz","{""Product Dimensions"": ""5.6 x 0.4 x 4.9 inches...",B00902T10Y,None,None,None
2,Digital Music,Lost in Love,5.000000,9,,,24.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Nastyboy Klick Format: Audio CD,"CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore","{""Package Dimensions"": ""4.7 x 4.6 x 0.1 inches...",B00000DALY,None,None,None
3,Digital Music,Somewhere in Time,4.800781,1186,,The 1980 soundtrack to the now classic motion ...,11.55,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}","John Barry (Composer), Barry, John (Comp...","CDs & Vinyl, Soundtracks, Movie Scores","{""Is Discontinued By Manufacturer"": ""No"", ""Lan...",B0000086D1,None,None,None
4,Digital Music,Kimmon Waldruff,5.000000,1,,Solo acoustic fingerstyle guitar.,14.07,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Kimmon Waldruff (Artist) Format: Audio CD,"CDs & Vinyl, Folk","{""Is Discontinued By Manufacturer"": ""No"", ""Pro...",B000S6W7KC,None,None,None

In [23]:
meta_df['main_category'].unique()
meta_df.shape

(701959, 16)

In [24]:
meta_df = meta_df.drop_duplicates(subset=['parent_asin'], keep='last')
meta_df.shape

(701959, 16)

In [25]:
# drop cols dont provide contextual meaning
meta = meta_df.drop(['images', 'features', 'videos', 'store', 'price', 'details', 'bought_together', 'subtitle', 'author'], axis='columns')
meta

,main_category,title,average_rating,rating_number,description,categories,parent_asin
0,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",B000002X4C
1,Digital Music,Rio Angie,5.000000,1,"Shrimp City Slim (aka Gary Erwin, b. 1953, Chi...","CDs & Vinyl, Jazz, Avant Garde & Free Jazz",B00902T10Y
2,Digital Music,Lost in Love,5.000000,9,,"CDs & Vinyl, Rap & Hip-Hop, Gangsta & Hardcore",B00000DALY
3,Digital Music,Somewhere in Time,4.800781,1186,The 1980 soundtrack to the now classic motion ...,"CDs & Vinyl, Soundtracks, Movie Scores",B0000086D1
4,Digital Music,Kimmon Waldruff,5.000000,1,Solo acoustic fingerstyle guitar.,"CDs & Vinyl, Folk",B000S6W7KC
...,...,...,...,...,...,...,...
701954,Digital Music,Forever Gold: British Invasion,3.000000,1,British Invasion ~ Forever Gold: British Invasion,"CDs & Vinyl, International Music, Europe, Brit...",B00005AVHN
701955,Digital Music,"Joan Hammond, Historical Recordings from 1941-49",5.000000,1,,"CDs & Vinyl, Classical",B000T001IM
701956,Digital Music,Come Alive,4.500000,4,The Second Full Length Album from the Winner o...,"CDs & Vinyl, International Music, Africa, Sout...",B00069I6RO
701957,Digital Music,Long Day in the Milky Way,4.398438,16,2020 release from the folk/Americana singer/so...,"CDs & Vinyl, Folk",B08BF2PH1X
701958,Digital Music,Genius of Valiha,3.000000,1,World Music Library 122. Track List: 1 Faly mi...,"CDs & Vinyl, International Music",B000001LW6

In [32]:
# merge df vs meta
merge = user_df2.merge(meta, on='parent_asin', how='right', suffixes=('', '_meta'))
merge.head(5)

,rating,asin,parent_asin,user_id,timestamp,text,main_category,title,average_rating,rating_number,description,categories
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Definitely the weakest of the three albums SWV...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Unlike It's About Time and New Beginning this ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,"Their third and final album as a group, &quot;...",Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
3,5.0,B000002X4C,B000002X4C,AE73R3KLFKXFNWUBOA4JCLT5UWKA,1.427480e+12,thank you,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
4,2.0,B000002X4C,B000002X4C,AFICHVZ62IFAWIBZK3U6B7NZWAVQ,1.289638e+12,When I was trying to decide whether or not to ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"

In [33]:
merge.columns = [
    'rating', 'iid', 'parent_iid', 'uid', 'timestamp', 'reviews',
    'main_category', 'title', 'average_rating', 'rating_number',
    'description', 'categories'
]

In [34]:
merge.shape

(4827559, 12)

In [35]:
# Check unique counts
merge.iid.nunique(), merge.parent_iid.unique(), merge.uid.nunique()

(701706,
 array(['B000002X4C', 'B00902T10Y', 'B00000DALY', ..., 'B00069I6RO',
        'B08BF2PH1X', 'B000001LW6'], dtype=object),
 1754118)

In [36]:
merge.head(3)

,rating,iid,parent_iid,uid,timestamp,reviews,main_category,title,average_rating,rating_number,description,categories
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Definitely the weakest of the three albums SWV...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Unlike It's About Time and New Beginning this ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,"Their third and final album as a group, &quot;...",Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"

In [38]:
merge_df = merge.copy()
merge_df = merge_df.rename(columns={'title': 'title_review'})
# merged_df['timestamp'] = pd.to_datetime(merged_df['timestamp'], unit='ms')
merge_df.head(5)

,rating,iid,parent_iid,uid,timestamp,reviews,main_category,title_review,average_rating,rating_number,description,categories
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Definitely the weakest of the three albums SWV...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Unlike It's About Time and New Beginning this ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,"Their third and final album as a group, &quot;...",Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
3,5.0,B000002X4C,B000002X4C,AE73R3KLFKXFNWUBOA4JCLT5UWKA,1.427480e+12,thank you,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"
4,2.0,B000002X4C,B000002X4C,AFICHVZ62IFAWIBZK3U6B7NZWAVQ,1.289638e+12,When I was trying to decide whether or not to ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House"

In [ ]:
# filter merge_df with rating >= 4
# merged_df['like'] = merged_df['rating'] >= 4 

# data.drop_duplicates(subset=['asin'])

In [39]:
item_info = merge_df.groupby('iid').agg({"rating_number": 'first'})
user_info = merge_df.groupby('uid').agg({"rating": 'count'})

active_item = item_info[item_info['rating_number'] > 5].index
active_user = user_info[user_info['rating'] > 5].index
active_item.shape, active_user.shape

((452791,), (142425,))

In [40]:
merge_df = merge_df[merge_df['uid'].isin(active_user) & merge_df['iid'].isin(active_item)]

In [41]:
merge_df['label'] = 0
merge_df.loc[merge_df['rating'] >= 4, 'label'] = 1

In [42]:
merge_df.head(3)

,rating,iid,parent_iid,uid,timestamp,reviews,main_category,title_review,average_rating,rating_number,description,categories,label
0,1.0,B000002X4C,B000002X4C,AGDQO4VIXXMHZMFRFHAHO2PNCYRQ,1.420266e+12,Definitely the weakest of the three albums SWV...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",0
1,1.0,B000002X4C,B000002X4C,AEYOPYIIRMWVY5BLNZKZFZFJFQRA,1.379363e+12,Unlike It's About Time and New Beginning this ...,Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",0
2,4.0,B000002X4C,B000002X4C,AHAIZWWINONHYU7A3FVCEH75R4CA,9.534267e+11,"Their third and final album as a group, &quot;...",Digital Music,Release Some Tension,4.601562,112,Swv ~ Release Some Tension,"CDs & Vinyl, Dance & Electronic, House",1

In [43]:
merge_df.shape

(2130048, 13)

In [44]:
sample_df = merge_df.sample(n=100000, random_state=42)

In [45]:
user_counts = sample_df['uid'].value_counts()

In [46]:
user_counts.shape

(58188,)

In [ ]:
# encode user_id and asin
# merged_df['user_id_encoded'] = LabelEncoder().fit_transform(merged_df['user_id'])
# merged_df['asin_encoded'] = LabelEncoder().fit_transform(merged_df['asin'])
# merged_df['parent_asin_encoded'] = LabelEncoder().fit_transform(merged_df['parent_asin'])

In [47]:
min_user_interactions = 2
qualified_users = user_counts[user_counts >= min_user_interactions].index
filtered_df = sample_df[sample_df['uid'].isin(qualified_users)].copy()
print(f"After filtering users with >= {min_user_interactions} interactions: {len(filtered_df)} interactions")
print(f"Qualified users: {len(qualified_users)}")

After filtering users with >= 2 interactions: 60763 interactions
Qualified users: 18951

In [48]:
# sort to ensure we take the most recent interaction for each user
filtered_df = filtered_df.sort_values(['uid', 'timestamp'])
test_data = filtered_df.groupby('uid').tail(1).copy()
train_data = filtered_df[~filtered_df.index.isin(test_data.index)].copy()
print("\nLeave-One-Out split results:")
print(f"Train: {train_data.shape[0]} interactions, {train_data['uid'].nunique()} users")
print(f"Test: {test_data.shape[0]} interactions, {test_data['uid'].nunique()} users")

Leave-One-Out split results:
Train: 41812 interactions, 18951 users
Test: 18951 interactions, 18951 users

In [49]:
train_items = set(train_data['iid'].unique())
test_items = set(test_data['iid'].unique())

# calculate % overlap 
overlap = train_items.intersection(test_items)
print(f"Item overlap: {len(overlap)}/{len(test_items)} ({len(overlap)/len(test_items):.1%})")

Item overlap: 4821/16401 (29.4%)

In [50]:
print("\nAdditional Diagnostics:")
print(f"Average interactions per user (train): {train_data.shape[0] / train_data['uid'].nunique():.1f}")
print(f"Average interactions per user (test): {test_data.shape[0] / test_data['uid'].nunique():.1f}")

# save to CSV files
train_data.to_csv('train_set_new.csv', index=False)
test_data.to_csv('test_set_new.csv', index=False)

Additional Diagnostics:
Average interactions per user (train): 2.2
Average interactions per user (test): 1.0